# The level of compression used for the tarballs in the cache. 
# Higher values result in better compression but slower installation.
compressionLevel: mixed

# The default range prefix used when adding new dependencies. 
# An empty string means exact versions will be used by default.
defaultSemverRangePrefix: ''

# If true, Yarn will display interactive prompts for certain operations, 
# like selecting the version of a package to install.
preferInteractive: true

# Specifies the type of node linker to use. 
# 'node-modules' means Yarn will use the classic node_modules folder structure.
nodeLinker: node-modules

# Path to the specific Yarn release to use. 
# This allows projects to lock down the exact version of Yarn being used.
yarnPath: .yarn/releases/yarn-3.6.0.cjs
