name: 'Update Version'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0 Note: without v)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Update Version Packages
        run: bash ./scripts/update-version.sh
        env:
          VERSION: ${{ github.event.inputs.version }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0' # By default do not run HUSKY install
